spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    schema: classpath:db/schema-h2.sql
#    data: classpath:db/data-h2.sql
    url: jdbc:mysql://10.50.162.178:28925/operation-system?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: admin
    password: yCRTqH3zOMPRm9clijr5